---
title: "EVD1"
author: "Louis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Set-up

```{r data-import, include=FALSE}
library(dplyr)
library(MASS)


# Keeps 'random' consistent
set.seed(123)

# Home dev
dat <- read.csv('C:\\Users\\louis\\OneDrive\\Documents\\Education\\NGED\\University Work\\Year 2\\Y2-R-Portfolio\\Data\\all_sm_data.csv')

# Work dev
#dat <- read.csv('C:\\Users\\Admin\\Documents\\NGED Work\\CDP Smart Meter Data\\Data\\all_sm_data.csv')
```

```{r filter-outliers}
remove_outliers <- function(df, column) {
  Q1 <- quantile(column, 0.25)
  Q3 <- quantile(column, 0.75)
  IQR <- Q3 - Q1
  
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q1 + 1.5 * IQR
  
  filtered_df <- df[column >= lower_bound & column <= upper_bound,]
  
  return(filtered_df)
}
```

## Histogram


```{r import_per_device_mle_norm}
dat$import_per_device <- dat$Total_consumption_active_import / dat$aggregated_device_count_Active

filt <- remove_outliers(dat, dat$import_per_device)

hist(filt$import_per_device, breaks = seq(min(filt$import_per_device), max(filt$import_per_device), length.out = 30))

# Fit normal distribution to the subset data
fit_norm <- fitdistr(filt$import_per_device, densfun = "normal")
print(fit_norm)

test_data <- rnorm(10000,mean=fit_norm$estimate['mean'],sd=fit_norm$estimate['sd'])
hist(test_data, breaks = 30)
```

```{r import_per_device_conf_int}
conf_intervals <- confint(fit_norm, level=0.95)

print(conf_intervals)
```

```{r import_per_device_mle_trunc_norm}
dat$import_per_device <- dat$Total_consumption_active_import / dat$aggregated_device_count_Active

filt <- remove_outliers(dat, dat$import_per_device)

hist(filt$import_per_device, breaks = seq(min(filt$import_per_device), max(filt$import_per_device), length.out = 30))

# Fit normal distribution to the subset data
fit_norm <- fitdistr(filt$import_per_device, densfun = "normal", lower=0)
print(fit_norm)

library(truncnorm)

# Generate random data from a truncated normal distribution with lower bound 0
test_data <- rtruncnorm(10000, a = 0, b = 500, mean = fit_norm$estimate[1], sd = fit_norm$estimate[2])
hist(test_data, breaks = 30)
```




```{r import_per_device_mle_gamma}
dat$import_per_device <- dat$Total_consumption_active_import / dat$aggregated_device_count_Active

filt <- remove_outliers(dat, dat$import_per_device)

filt$import_per_device <- filt$import_per_device + 1 # Ensures no 0 values

hist(filt$import_per_device, breaks = seq(min(filt$import_per_device), max(filt$import_per_device), length.out = 30))

# Fit normal distribution to the subset data
fit_gam <- fitdistr(filt$import_per_device,"gamma")
print(fit_gam)
```

```{r yuuhhh}
test_data <- rgamma(10000,shape=fit_gam$estimate['shape'],rate=fit_gam$estimate['rate'])
hist(test_data, breaks = 50)
```
